#!/usr/bin/env python

import os
import shutil
import stat

from os.path import exists, join


SRCDIR = 'kamaki'
DSTDIR = 'bin'
DST = 'kamaki'

FILES = ('config.py', 'utils.py', 'client.py', 'cli.py')


def cat(path, dst, skipheader=True):
    dst.write('\n')
    
    in_header = True
    for line in open(path):
        if in_header and line.strip() and not line.startswith('#'):
            in_header = False
        
        if line.startswith('from kamaki.'):
            continue    # Skip local imports
        
        if skipheader and in_header:
            continue
        
        dst.write(line)


def main():
    if not exists(DSTDIR):
        os.makedirs(DSTDIR)
    dstpath = join(DSTDIR, DST)
    
    dst = open(dstpath, 'w')
    
    dst.write('#!/usr/bin/env python\n')
    
    cat(join(SRCDIR, '__init__.py'), dst, skipheader=False)
    
    for file in FILES:
        cat(join(SRCDIR, file), dst)
    
    dst.close()
    
    # Make file executable
    mode = stat.S_IMODE(os.stat(dstpath).st_mode)
    mode |= 0111
    os.chmod(dstpath, mode)


if __name__ == '__main__':
    main()
